### ISSUE TITLE
ты блять пидорас или да?

### ISSUE THREAD

**Issue by 0susboy0** [HendrikPetertje/vimify#5]
нахуя ты украл мою идею, я тут главный по интеграциям спотифая, тебе ебало сломать или сам? 
![image](https://user-images.githubusercontent.com/47082914/67165994-1e441b00-f394-11e9-8e56-4147f45cab8a.png)
**УДАЛИСЬ БЫСТРО С ГИТХАБА**

**Comment by kesha1225** [comment]
Полностью поддерживаю, удаляй репу гнида

**Comment by 0susboy0** [comment]
@HendrikPetertje **ну ебать маРтЫшка, у тебя пару секунд, чтобы удалить репозиторий, или я тебя нахуй удалю из жизни**

**Comment by crinny** [comment]
Ненавижу таких наглых, бесстыжих воров идей.

**Comment by timoniq** [comment]
поддерживаю, согласен, какая-то непонятная репа что это вообще такое памагите!!!!

**Comment by 0susboy0** [comment]
- ### _**СУКА УДАЛЯЙ БЫСТРО ТЫ УЖЕ ВЫВОДИШЬ МЕНЯ ТУПОЙ АМЕРИКАНЕЦ УКРАЛ МОЮ РАЗРАБОТКУ СУКА**_

**Comment by newpotsdev** [comment]
я сам по началу ахуел но автору 30 лет

**Comment by newpotsdev** [comment]
автору исуса

**Comment by crinny** [comment]
УДАЛИ РЕПУ

**Comment by timoniq** [comment]
мапагити!!!!!

**Comment by prostomarkeloff** [comment]
russian idiots

**Comment by timoniq** [comment]
@prostomarkeloff ты на каво напал американский агент

**Comment by 0susboy0** [comment]
@timoniq **СРАЗУ ВИДНО ### ПА ТРИ ОТ**

**Comment by mrqiz** [comment]
![image](https://user-images.githubusercontent.com/49580687/67219483-ce676180-f430-11e9-96ff-b6c4fc7e9251.png)

**Comment by mrqiz** [comment]
@prostomarkeloff чё ты там сказала америкванская свинья
