### ISSUE TITLE
Удαли peпy быcтpo

### ISSUE THREAD

**Issue by crinny** [HendrikPetertje/vimify#6]
Дyмa𝚎шь, yдaлͷл нaш Issu𝚎 и мы oтⲥтαнeм? Heт.
P.S. Don't report my account as this issue is a joke

**Comment by timoniq** [comment]
согласен что за несправедливое удаление Issue

**Comment by linker-git** [comment]
да!

**Comment by swedishthieft** [comment]
swedishthieft.github.io

глянь, что мы достали из твоей головы!
